name = "GridVisualizeTools"
uuid = "5573ae12-3b76-41d9-b48c-81d0b6e61cc5"
authors = ["JÃ¼rgen Fuhrmann <juergen-fuhrmann@web.de>"]
version = "0.3.0"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"

[compat]
ColorSchemes = "3"
Colors = "0.12"
DocStringExtensions = "0.8, 0.9"
StaticArraysCore = "1.4"
julia = "1.6"
